project_name: devbox
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/devbox/main.go
    binary: devbox
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}" # For reproducible builds
    ldflags:
      - -s -w
      - -X go.jetify.com/devbox/internal/build.Version={{.Version}}
      - -X go.jetify.com/devbox/internal/build.Commit={{.Commit}}
      - -X go.jetify.com/devbox/internal/build.CommitDate={{.CommitDate}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    goarm:
      - 7
archives:
  - files:
      - no-files-will-match-* # Glob that does not match to create archive with only binaries.
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if eq .Arch "arm" }}v{{ .Arm }}l{{ end }}'
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
release:
  prerelease: auto
  draft: true
  mode: keep-existing
  replace_existing_draft: false
  use_existing_draft: true
  replace_existing_artifacts: true
